# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c90aacc851b1b061a9782bb1f158c841fa299dd7de4282c17d6edd3438642c39957569e5a1b1899afad37ae362725aa808a40ac5d07d1f475d8ac002642dad97

test:
  secret_key_base: 09b9ec4973a6f424cb0fa0eb77a3794bb34e25707badfeddb8e805e262bb0d9e44f916e9b8d5d22b2f512a7e0a2c60461e72112ff5fd8b628b59b3bc89329d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
